[package]
name = "resource_monitor"
version = "0.1.0"
edition = "2021"

[lib]
name = "resource_monitor"
path = "src/lib.rs"

[dependencies]
sysinfo = { workspace = true }
tokio = { workspace = true }
common = { path = "../common" }
tracing = { workspace = true }
