version: '3.8'

services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUNNER_VERSION: 2.311.0
    image: aurelia-runner:latest
    container_name: aurelia-runner
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_OWNER=${GITHUB_OWNER:-tricorefile}
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY:-aurelia}
      - RUNNER_NAME=${RUNNER_NAME:-aurelia-runner}
      - RUNNER_LABELS=${RUNNER_LABELS:-self-hosted,linux,x64,docker,aurelia}
      - RUNNER_WORKDIR=${RUNNER_WORKDIR:-_work}
    volumes:
      # Mount Docker socket for Docker-in-Docker operations
      - /var/run/docker.sock:/var/run/docker.sock
      # Persistent storage for work directory
      - ./work:/home/runner/_work
      # SSH keys for deployment (optional)
      - ./ssh:/home/runner/.ssh:ro
    restart: unless-stopped
    networks:
      - runner-network

networks:
  runner-network:
    driver: bridge