name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      server_ip:
        description: 'Target server IP (leave empty to use default)'
        required: false
        default: ''
      release_tag:
        description: 'Release tag to deploy (default: latest)'
        required: false
        default: 'latest'

jobs:
  deploy-from-release:
    name: Deploy from GitHub Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name: Deploy using smart deploy script
        if: ${{ secrets.SSH_PRIVATE_KEY != '' }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ github.event.inputs.server_ip || secrets.DEFAULT_SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER || 'ubuntu' }}
          RELEASE_TAG: ${{ github.event.inputs.release_tag || 'latest' }}
        run: |
          # Setup SSH key
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          
          # Run smart deployment
          python3 py/smart_deploy.py \
            "$SERVER_IP" \
            --user "$SERVER_USER" \
            --key ~/.ssh/deploy_key \
            --tag "$RELEASE_TAG" \
            --path "/opt/aurelia"
          
          echo "Deployment completed!"

      - name: Manual deployment instructions
        if: ${{ secrets.SSH_PRIVATE_KEY == '' }}
        run: |
          echo "======================================"
          echo "  Manual Deployment Instructions"
          echo "======================================"
          echo ""
          echo "To deploy Aurelia to your server, run:"
          echo ""
          echo "# Using bash script:"
          echo "./scripts/smart_deploy.sh latest YOUR_SERVER_IP"
          echo ""
          echo "# Or using Python script:"
          echo "python3 py/smart_deploy.py YOUR_SERVER_IP --tag latest"
          echo ""
          echo "The script will:"
          echo "1. Detect your server's architecture"
          echo "2. Download the appropriate binary from GitHub releases"
          echo "3. Deploy and start the service"
          echo ""
          echo "Required GitHub Secrets for automatic deployment:"
          echo "- SSH_PRIVATE_KEY: Your SSH private key"
          echo "- DEFAULT_SERVER_IP: Default server IP address"
          echo "- SERVER_USER: SSH username (optional, defaults to 'ubuntu')"